version: '3'

services:
  burstcoin:
    image: burstcoin/core:1.3.6cg-mariadb
    restart: always
    depends_on:
     - mariadb
    ports:
     - 8123:8123
     - 8125:8125
  mariadb:
    image: mariadb:10
    environment:
     - MYSQL_ROOT_PASSWORD=burstwallet
     - MYSQL_DATABASE=burstwallet
    volumes:
     - ./burst_db:/var/lib/mysql
